# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clusterMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='clusterMessages.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x63lusterMessages.proto\x1a\x19google/protobuf/any.proto\"T\n\x07Message\x12\"\n\nsenderInfo\x18\x01 \x01(\x0b\x32\x0e.NodeInfoProto\x12%\n\x07message\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"\xa9\x01\n\rNodeInfoProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x13\n\x0bincarnation\x18\x04 \x01(\x05\x12)\n\x06health\x18\x05 \x01(\x0e\x32\x19.NodeInfoProto.NodeHealth\".\n\nNodeHealth\x12\x08\n\x04\x44\x45\x41\x44\x10\x00\x12\x0b\n\x07SUSPECT\x10\x02\x12\t\n\x05\x41LIVE\x10\x04\"*\n\x04Ping\x12\"\n\ntargetInfo\x18\x01 \x01(\x0b\x32\x0e.NodeInfoProto\"-\n\x07PingReq\x12\"\n\ntargetInfo\x18\x01 \x01(\x0b\x32\x0e.NodeInfoProto\"\x05\n\x03\x41\x63k\"\r\n\x0bJoinRequest\"/\n\nJoinAccept\x12!\n\x0bnetworkView\x18\x01 \x01(\x0b\x32\x0c.NetworkView\"h\n\x06Gossip\x12\"\n\noriginNode\x18\x01 \x01(\x0b\x32\x0e.NodeInfoProto\x12\x13\n\x0bmessageType\x18\x02 \x01(\t\x12%\n\x07message\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\",\n\x0bNetworkView\x12\x1d\n\x05nodes\x18\x01 \x03(\x0b\x32\x0e.NodeInfoProtob\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])



_NODEINFOPROTO_NODEHEALTH = _descriptor.EnumDescriptor(
  name='NodeHealth',
  full_name='NodeInfoProto.NodeHealth',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEAD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUSPECT', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALIVE', index=2, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=262,
  serialized_end=308,
)
_sym_db.RegisterEnumDescriptor(_NODEINFOPROTO_NODEHEALTH)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='senderInfo', full_name='Message.senderInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='Message.message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=136,
)


_NODEINFOPROTO = _descriptor.Descriptor(
  name='NodeInfoProto',
  full_name='NodeInfoProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='NodeInfoProto.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='NodeInfoProto.host', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='NodeInfoProto.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='incarnation', full_name='NodeInfoProto.incarnation', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='health', full_name='NodeInfoProto.health', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NODEINFOPROTO_NODEHEALTH,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=308,
)


_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='targetInfo', full_name='Ping.targetInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=352,
)


_PINGREQ = _descriptor.Descriptor(
  name='PingReq',
  full_name='PingReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='targetInfo', full_name='PingReq.targetInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=399,
)


_ACK = _descriptor.Descriptor(
  name='Ack',
  full_name='Ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=406,
)


_JOINREQUEST = _descriptor.Descriptor(
  name='JoinRequest',
  full_name='JoinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=421,
)


_JOINACCEPT = _descriptor.Descriptor(
  name='JoinAccept',
  full_name='JoinAccept',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='networkView', full_name='JoinAccept.networkView', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=470,
)


_GOSSIP = _descriptor.Descriptor(
  name='Gossip',
  full_name='Gossip',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='originNode', full_name='Gossip.originNode', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messageType', full_name='Gossip.messageType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='Gossip.message', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=576,
)


_NETWORKVIEW = _descriptor.Descriptor(
  name='NetworkView',
  full_name='NetworkView',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='NetworkView.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=578,
  serialized_end=622,
)

_MESSAGE.fields_by_name['senderInfo'].message_type = _NODEINFOPROTO
_MESSAGE.fields_by_name['message'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_NODEINFOPROTO.fields_by_name['health'].enum_type = _NODEINFOPROTO_NODEHEALTH
_NODEINFOPROTO_NODEHEALTH.containing_type = _NODEINFOPROTO
_PING.fields_by_name['targetInfo'].message_type = _NODEINFOPROTO
_PINGREQ.fields_by_name['targetInfo'].message_type = _NODEINFOPROTO
_JOINACCEPT.fields_by_name['networkView'].message_type = _NETWORKVIEW
_GOSSIP.fields_by_name['originNode'].message_type = _NODEINFOPROTO
_GOSSIP.fields_by_name['message'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_NETWORKVIEW.fields_by_name['nodes'].message_type = _NODEINFOPROTO
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['NodeInfoProto'] = _NODEINFOPROTO
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['PingReq'] = _PINGREQ
DESCRIPTOR.message_types_by_name['Ack'] = _ACK
DESCRIPTOR.message_types_by_name['JoinRequest'] = _JOINREQUEST
DESCRIPTOR.message_types_by_name['JoinAccept'] = _JOINACCEPT
DESCRIPTOR.message_types_by_name['Gossip'] = _GOSSIP
DESCRIPTOR.message_types_by_name['NetworkView'] = _NETWORKVIEW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'clusterMessages_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  ))
_sym_db.RegisterMessage(Message)

NodeInfoProto = _reflection.GeneratedProtocolMessageType('NodeInfoProto', (_message.Message,), dict(
  DESCRIPTOR = _NODEINFOPROTO,
  __module__ = 'clusterMessages_pb2'
  # @@protoc_insertion_point(class_scope:NodeInfoProto)
  ))
_sym_db.RegisterMessage(NodeInfoProto)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), dict(
  DESCRIPTOR = _PING,
  __module__ = 'clusterMessages_pb2'
  # @@protoc_insertion_point(class_scope:Ping)
  ))
_sym_db.RegisterMessage(Ping)

PingReq = _reflection.GeneratedProtocolMessageType('PingReq', (_message.Message,), dict(
  DESCRIPTOR = _PINGREQ,
  __module__ = 'clusterMessages_pb2'
  # @@protoc_insertion_point(class_scope:PingReq)
  ))
_sym_db.RegisterMessage(PingReq)

Ack = _reflection.GeneratedProtocolMessageType('Ack', (_message.Message,), dict(
  DESCRIPTOR = _ACK,
  __module__ = 'clusterMessages_pb2'
  # @@protoc_insertion_point(class_scope:Ack)
  ))
_sym_db.RegisterMessage(Ack)

JoinRequest = _reflection.GeneratedProtocolMessageType('JoinRequest', (_message.Message,), dict(
  DESCRIPTOR = _JOINREQUEST,
  __module__ = 'clusterMessages_pb2'
  # @@protoc_insertion_point(class_scope:JoinRequest)
  ))
_sym_db.RegisterMessage(JoinRequest)

JoinAccept = _reflection.GeneratedProtocolMessageType('JoinAccept', (_message.Message,), dict(
  DESCRIPTOR = _JOINACCEPT,
  __module__ = 'clusterMessages_pb2'
  # @@protoc_insertion_point(class_scope:JoinAccept)
  ))
_sym_db.RegisterMessage(JoinAccept)

Gossip = _reflection.GeneratedProtocolMessageType('Gossip', (_message.Message,), dict(
  DESCRIPTOR = _GOSSIP,
  __module__ = 'clusterMessages_pb2'
  # @@protoc_insertion_point(class_scope:Gossip)
  ))
_sym_db.RegisterMessage(Gossip)

NetworkView = _reflection.GeneratedProtocolMessageType('NetworkView', (_message.Message,), dict(
  DESCRIPTOR = _NETWORKVIEW,
  __module__ = 'clusterMessages_pb2'
  # @@protoc_insertion_point(class_scope:NetworkView)
  ))
_sym_db.RegisterMessage(NetworkView)


# @@protoc_insertion_point(module_scope)
