# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class Address(google___protobuf___message___Message):
    host = ... # type: typing___Text
    port = ... # type: int

    def __init__(self,
        host : typing___Optional[typing___Text] = None,
        port : typing___Optional[int] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Address: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"host",u"port"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[b"host",b"port"]) -> None: ...
