# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0emessages.proto\x1a\x19google/protobuf/any.proto\"T\n\x07Message\x12\"\n\nsenderInfo\x18\x01 \x01(\x0b\x32\x0e.NodeInfoProto\x12%\n\x07message\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"%\n\x07\x41\x64\x64ress\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"\xe1\x01\n\rNodeInfoProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x04\x61\x64\x64r\x18\x02 \x01(\x0b\x32\x08.Address\x12\x1d\n\x0bgossip_addr\x18\x03 \x01(\x0b\x32\x08.Address\x12\x1b\n\tswim_addr\x18\x04 \x01(\x0b\x32\x08.Address\x12\x13\n\x0bincarnation\x18\x05 \x01(\x05\x12)\n\x06health\x18\x06 \x01(\x0e\x32\x19.NodeInfoProto.NodeHealth\".\n\nNodeHealth\x12\x08\n\x04\x44\x45\x41\x44\x10\x00\x12\x0b\n\x07SUSPECT\x10\x02\x12\t\n\x05\x41LIVE\x10\x04\";\n\x04Ping\x12\x12\n\ntargetName\x18\x01 \x01(\t\x12\x1f\n\rtargetAddress\x18\x02 \x01(\x0b\x32\x08.Address\">\n\x07PingReq\x12\x12\n\ntargetName\x18\x01 \x01(\t\x12\x1f\n\rtargetAddress\x18\x02 \x01(\x0b\x32\x08.Address\"\x05\n\x03\x41\x63k\"}\n\x06Gossip\x12\"\n\noriginNode\x18\x01 \x01(\x0b\x32\x0e.NodeInfoProto\x12\x16\n\x0eremainingSends\x18\x02 \x01(\x05\x12\x10\n\x08gossipId\x18\x03 \x01(\t\x12%\n\x07message\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\",\n\x0bNetworkView\x12\x1d\n\x05nodes\x18\x01 \x03(\x0b\x32\x0e.NodeInfoProtob\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])



_NODEINFOPROTO_NODEHEALTH = _descriptor.EnumDescriptor(
  name='NodeHealth',
  full_name='NodeInfoProto.NodeHealth',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEAD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUSPECT', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALIVE', index=2, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=350,
  serialized_end=396,
)
_sym_db.RegisterEnumDescriptor(_NODEINFOPROTO_NODEHEALTH)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='senderInfo', full_name='Message.senderInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='Message.message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=129,
)


_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='Address.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='Address.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=168,
)


_NODEINFOPROTO = _descriptor.Descriptor(
  name='NodeInfoProto',
  full_name='NodeInfoProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='NodeInfoProto.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addr', full_name='NodeInfoProto.addr', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gossip_addr', full_name='NodeInfoProto.gossip_addr', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='swim_addr', full_name='NodeInfoProto.swim_addr', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='incarnation', full_name='NodeInfoProto.incarnation', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='health', full_name='NodeInfoProto.health', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NODEINFOPROTO_NODEHEALTH,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=396,
)


_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='targetName', full_name='Ping.targetName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='targetAddress', full_name='Ping.targetAddress', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=398,
  serialized_end=457,
)


_PINGREQ = _descriptor.Descriptor(
  name='PingReq',
  full_name='PingReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='targetName', full_name='PingReq.targetName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='targetAddress', full_name='PingReq.targetAddress', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=521,
)


_ACK = _descriptor.Descriptor(
  name='Ack',
  full_name='Ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=523,
  serialized_end=528,
)


_GOSSIP = _descriptor.Descriptor(
  name='Gossip',
  full_name='Gossip',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='originNode', full_name='Gossip.originNode', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remainingSends', full_name='Gossip.remainingSends', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gossipId', full_name='Gossip.gossipId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='Gossip.message', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=655,
)


_NETWORKVIEW = _descriptor.Descriptor(
  name='NetworkView',
  full_name='NetworkView',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='NetworkView.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=657,
  serialized_end=701,
)

_MESSAGE.fields_by_name['senderInfo'].message_type = _NODEINFOPROTO
_MESSAGE.fields_by_name['message'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_NODEINFOPROTO.fields_by_name['addr'].message_type = _ADDRESS
_NODEINFOPROTO.fields_by_name['gossip_addr'].message_type = _ADDRESS
_NODEINFOPROTO.fields_by_name['swim_addr'].message_type = _ADDRESS
_NODEINFOPROTO.fields_by_name['health'].enum_type = _NODEINFOPROTO_NODEHEALTH
_NODEINFOPROTO_NODEHEALTH.containing_type = _NODEINFOPROTO
_PING.fields_by_name['targetAddress'].message_type = _ADDRESS
_PINGREQ.fields_by_name['targetAddress'].message_type = _ADDRESS
_GOSSIP.fields_by_name['originNode'].message_type = _NODEINFOPROTO
_GOSSIP.fields_by_name['message'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_NETWORKVIEW.fields_by_name['nodes'].message_type = _NODEINFOPROTO
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Address'] = _ADDRESS
DESCRIPTOR.message_types_by_name['NodeInfoProto'] = _NODEINFOPROTO
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['PingReq'] = _PINGREQ
DESCRIPTOR.message_types_by_name['Ack'] = _ACK
DESCRIPTOR.message_types_by_name['Gossip'] = _GOSSIP
DESCRIPTOR.message_types_by_name['NetworkView'] = _NETWORKVIEW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  ))
_sym_db.RegisterMessage(Message)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESS,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:Address)
  ))
_sym_db.RegisterMessage(Address)

NodeInfoProto = _reflection.GeneratedProtocolMessageType('NodeInfoProto', (_message.Message,), dict(
  DESCRIPTOR = _NODEINFOPROTO,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:NodeInfoProto)
  ))
_sym_db.RegisterMessage(NodeInfoProto)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), dict(
  DESCRIPTOR = _PING,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:Ping)
  ))
_sym_db.RegisterMessage(Ping)

PingReq = _reflection.GeneratedProtocolMessageType('PingReq', (_message.Message,), dict(
  DESCRIPTOR = _PINGREQ,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:PingReq)
  ))
_sym_db.RegisterMessage(PingReq)

Ack = _reflection.GeneratedProtocolMessageType('Ack', (_message.Message,), dict(
  DESCRIPTOR = _ACK,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:Ack)
  ))
_sym_db.RegisterMessage(Ack)

Gossip = _reflection.GeneratedProtocolMessageType('Gossip', (_message.Message,), dict(
  DESCRIPTOR = _GOSSIP,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:Gossip)
  ))
_sym_db.RegisterMessage(Gossip)

NetworkView = _reflection.GeneratedProtocolMessageType('NetworkView', (_message.Message,), dict(
  DESCRIPTOR = _NETWORKVIEW,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:NetworkView)
  ))
_sym_db.RegisterMessage(NetworkView)


# @@protoc_insertion_point(module_scope)
